name: Ejecutar Buscador de Noticias

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  buscar_noticias:
    runs-on: ubuntu-latest
    container:
      image: zombis234/ollama-python:latest
      options: --privileged  # Necesario para que funcione Ollama

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar dependencias del proyecto
        run: pip install -r Backend/requirements.txt

      - name: Iniciar Ollama en segundo plano
        run: |
          ollama serve &  # inicia el servidor en segundo plano
          sleep 10        # espera a que se levante correctamente

      - name: Descargar modelo de Ollama
        run: ollama pull deepseek-coder-v2:16b

      - name: Ejecutar el script buscador.py
        run: python3 Backend/buscador.py
        env:
          API_KEY_GOOGLE_NEWS: ${{ secrets.API_KEY }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ALGORITHM: ${{ secrets.ALGORITHM }}
