name: Ejecutar Buscador de Noticias

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  buscar_noticias:
    runs-on: ubuntu-latest
    services:
      ollama:
        image: ollama/ollama:latest
        ports:
          - 11434:11434
        #   volumes: # Remove or comment out volumes, unless you have a very specific need to persist data between runs
        #     - ollama_data:/root/.ollama
    #    container:
    #      name: ollama
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.1'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r Backend/requirements.txt
          pip install feedparser
          pip install python-dotenv
          pip install ollama

      - name: Ejecutar el script buscador.py
        run: python Backend/buscador.py
        env:
          API_KEY_GOOGLE_NEWS: ${{ secrets.API_KEY }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ALGORITHM: ${{ secrets.ALGORITHM }}
