name: Ingestar noticias con IA

on:
  workflow_dispatch:

jobs:
  run-ingestion:
    runs-on: ubuntu-latest

    services:
      ollama:
        image: ollama/ollama:latest
        ports:
          - 11434:11434
        options: >-
          --health-cmd "curl -f http://localhost:11434 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalar Python y dependencias
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar requirements
        run: pip install -r requirements.txt

      - name: Esperar a que Ollama esté disponible
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:11434 | grep -q "Ollama"; then
              echo "✅ Ollama está disponible."
              break
            fi
            echo "⏳ Esperando a que Ollama esté disponible..."
            sleep 2
          done

      - name: Descargar modelo deepseek-coder-v2:16b
        run: |
          curl http://localhost:11434/api/pull \
            -d '{"name": "deepseek-coder-v2:16b"}' \
            -H "Content-Type: application/json"

      - name: Ejecutar script Python
        run: python Backend/buscador.py
