name: Ejecutar Buscador de Noticias

on:
  schedule:
    - cron: '0 14 * * *'  # Cada día a las 14:00 UTC
  workflow_dispatch:

jobs:
  buscar_noticias:
    runs-on: ubuntu-latest
    container:
      image: zombis234/ollama-python:latest
      options: --privileged  # Necesario para usar Ollama

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar dependencias del proyecto
        run: pip install -r Backend/requirements.txt

      - name: Iniciar Ollama en segundo plano y esperar a que esté disponible
        run: |
          ollama serve &

          echo "Esperando que Ollama esté disponible en localhost:11434..."
          for i in {1..30}; do
            if curl -s http://localhost:11434 > /dev/null; then
              echo "Ollama está listo."
              break
            fi
            echo "Esperando... ($i)"
            sleep 2
          done

      - name: Descargar modelo (deepseek-coder-v2:16b)
        run: ollama pull deepseek-coder-v2:16b

      - name: Ejecutar el script buscador.py
        run: python Backend/buscador.py
        env:
          API_KEY_GOOGLE_NEWS: ${{ secrets.API_KEY }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ALGORITHM: ${{ secrets.ALGORITHM }}
